
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.backend.compiladores.services;

/** CUP generated interface containing symbol constants. */
public interface ParserSym {
  /* terminals */
  public static final int IMPRIMIR_SIN_SALTO = 62;
  public static final int NUMERO = 14;
  public static final int FUNCTION = 58;
  public static final int END_FOR = 48;
  public static final int TIPO = 21;
  public static final int IMPRIMIR = 61;
  public static final int FIN_METODO = 56;
  public static final int CASE = 42;
  public static final int DIFERENTE = 32;
  public static final int METODO = 55;
  public static final int RESTA = 5;
  public static final int LPAREN = 10;
  public static final int FOR = 46;
  public static final int FIN = 3;
  public static final int RCOR = 13;
  public static final int RPAREN = 11;
  public static final int NOT = 35;
  public static final int MENORIGUAL = 30;
  public static final int AND = 34;
  public static final int IGUAL = 31;
  public static final int CARACTER = 17;
  public static final int INCREMENTAL = 49;
  public static final int LQUE = 44;
  public static final int OR = 33;
  public static final int COMO = 20;
  public static final int SELECT = 41;
  public static final int SUMA = 4;
  public static final int ELSE_IF = 40;
  public static final int IF = 36;
  public static final int END_WHILE = 51;
  public static final int MAYORIGUAL = 29;
  public static final int EOF = 0;
  public static final int BOOLEAN = 16;
  public static final int RETURN = 54;
  public static final int END_SELECT = 43;
  public static final int error = 1;
  public static final int COMA = 23;
  public static final int CADENA = 15;
  public static final int COMENTARIO = 25;
  public static final int MODULO = 9;
  public static final int SEMI_COLON = 24;
  public static final int MENOR = 28;
  public static final int END_IF = 38;
  public static final int DIVI = 7;
  public static final int ERROR = 63;
  public static final int ASIGNACION = 26;
  public static final int MAYOR = 27;
  public static final int CON_VALOR = 22;
  public static final int POTENCIA = 8;
  public static final int HASTA_QUE = 53;
  public static final int ELSE = 39;
  public static final int VARIABLE = 19;
  public static final int INGRESAR = 18;
  public static final int TO = 47;
  public static final int WHILE = 50;
  public static final int LCOR = 12;
  public static final int THEN = 37;
  public static final int REPETIR = 52;
  public static final int RQUE = 45;
  public static final int CON_PARAMETROS = 57;
  public static final int MULTI = 6;
  public static final int END_FUNCTION = 59;
  public static final int INICIO = 2;
  public static final int EJECUTAR = 60;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "INICIO",
  "FIN",
  "SUMA",
  "RESTA",
  "MULTI",
  "DIVI",
  "POTENCIA",
  "MODULO",
  "LPAREN",
  "RPAREN",
  "LCOR",
  "RCOR",
  "NUMERO",
  "CADENA",
  "BOOLEAN",
  "CARACTER",
  "INGRESAR",
  "VARIABLE",
  "COMO",
  "TIPO",
  "CON_VALOR",
  "COMA",
  "SEMI_COLON",
  "COMENTARIO",
  "ASIGNACION",
  "MAYOR",
  "MENOR",
  "MAYORIGUAL",
  "MENORIGUAL",
  "IGUAL",
  "DIFERENTE",
  "OR",
  "AND",
  "NOT",
  "IF",
  "THEN",
  "END_IF",
  "ELSE",
  "ELSE_IF",
  "SELECT",
  "CASE",
  "END_SELECT",
  "LQUE",
  "RQUE",
  "FOR",
  "TO",
  "END_FOR",
  "INCREMENTAL",
  "WHILE",
  "END_WHILE",
  "REPETIR",
  "HASTA_QUE",
  "RETURN",
  "METODO",
  "FIN_METODO",
  "CON_PARAMETROS",
  "FUNCTION",
  "END_FUNCTION",
  "EJECUTAR",
  "IMPRIMIR",
  "IMPRIMIR_SIN_SALTO",
  "ERROR"
  };
}

